name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.*
          terraform_wrapper: false
      - run: go mod download
      - run: go test -v -cover ./...
        env:
          TF_ACC: ${{ github.ref == 'refs/heads/main' && '1' || '' }}
          TF_VAR_HATENABLOG_APIKEY: ${{ secrets.HATENABLOG_APIKEY }}
